Repository AY2425S2-CS2103T-W12-3/tp, pull requests merged in 2025-04, with the labels that each got.

#149 Fix bug with log and sort
  src/main/java/seedu/address/logic/commands/LogCommand.java
Labels: type.Bug, severity.Medium

#153 Duplicate entries by ID instead of name
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: type.Task, severity.Medium

#156 Update log ui to enhance app
  src/main/resources/view/LogBox.css
  src/main/resources/view/PersonListCard.fxml
Labels: priority.Medium

#152 Branch update ug sort filter
  docs/UserGuide.md
  docs/images/Filter_usage.png
  docs/images/filterProjectExample.png
  docs/images/filterTagExample.png
  docs/images/sortFilterCommandExample.png
Labels: type.Task

#160 Fix issue of clearconfirmationwindow not closing when main program is closed first
  src/main/java/seedu/address/ui/MainWindow.java
Labels: alpha-bug

#161 Update uml to match delete command
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
Labels: type.Task

#166 Rename instances of AddressBook in Developer Guide to Profiler
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/SortSequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram-Logic.puml
  docs/diagrams/UndoSequenceDiagram-Model.puml
  docs/diagrams/tracing/LogicSequenceDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/CommitActivityDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ParserClasses.png
  docs/images/SortSequenceDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/UndoSequenceDiagram-Logic.png
  docs/images/UndoSequenceDiagram-Model.png
Labels: type.Task

#172 Fix delete command bug
  src/main/java/seedu/address/commons/core/index/Index.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/commons/core/index/IndexTest.java
Labels: type.Bug, severity.Medium, alpha-bug

#167 Update clear command in UG
  docs/UserGuide.md
Labels: type.Task

#173 Update Id to accept case-insensitive and store as upper case
  src/main/java/seedu/address/model/person/Id.java
  src/test/java/seedu/address/model/person/IdTest.java
Labels: type.Bug, severity.Medium, alpha-bug

#185 Update UG/ helpwindow/ delete command format
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
Labels: alpha-bug

#181 Fix duplicate clear command handling
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/ui/ClearConfirmationWindow.java
  src/main/java/seedu/address/ui/ConfirmationWindow.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/ui/ClearConfirmationWindowStub.java
  src/test/java/seedu/address/ui/ConfirmationWindowFactoryTest.java
Labels: alpha-bug

#188 Reject duplicate Log prefixes
  src/main/java/seedu/address/logic/parser/LogCommandParser.java
  src/test/java/seedu/address/logic/parser/LogCommandParserTest.java
Labels: alpha-bug

#189 Change filter behavior
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/model/person/ProjectContainsKeywordsPredicate.java
  src/test/java/seedu/address/model/person/ProjectContainsKeywordsPredicateTest.java
Labels: severity.Low, alpha-bug

#203 Rename AB3 mentions
  docs/DevOps.md
  docs/_config.yml
  docs/_data/projects.yml
  docs/index.md
Labels: alpha-bug

#198 Update Filter usage message and error message
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
Labels: severity.Low, alpha-bug

#199 Update progress success message to be more intuitive
  src/main/java/seedu/address/logic/commands/ProgressCommand.java
  src/test/java/seedu/address/logic/commands/ProgressCommandTest.java
Labels: severity.Low, alpha-bug

#209 Fix dark theme UI bug
  src/main/resources/view/HelpWindow.css
Labels: alpha-bug

#215 Add planned enhancement for filter command
  docs/DeveloperGuide.md
Labels: severity.Low

#269 Update UG bugs + sample data entries
  build.gradle
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/filterProjectExample.png
  docs/images/filterTagExample.png
  docs/images/findAlexDavidResult.png
  docs/images/helpMessage.png
  docs/images/sortFilterCommandExample.png
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: type.Bug, severity.Low

#274 Fix sort message and update UG clarity
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/SortCommand.java
Labels: severity.Low

#279 Fix error messages, planned enhancements, phone number constraint to 3-15 digits
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/tag/Tag.java
Labels: severity.Low

#280 Fix typo in DG and updated Ui images
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/filterTagExample.png
  docs/images/findAlexDavidResult.png
  docs/images/lightUI.png
  src/main/java/seedu/address/logic/commands/HelpCommand.java
Labels: severity.Low

#281 Remove unnecessary parts of DG
  docs/DeveloperGuide.md
Labels: severity.Low
